server {
       server_name hono-base.web.id;

         # 🔥 Block bad bots (lebih dulu = lebih hemat resource)
    if ($http_user_agent ~* (censys|scanner|xpanse|paloalto|sqlmap|nikto)) {
        return 444;
    }

        limit_req zone=req_limit burst=200 nodelay;
        limit_conn conn_limit 100;

        # Redirect HTTP ke HTTPS (jika menggunakan SSL)
        # return 301 https://$host$request_uri;

        # Allow bigger headers (fix upstream sent too big header)
        proxy_buffer_size          256k;
        proxy_buffers              4 512k;
        proxy_busy_buffers_size    512k;
        large_client_header_buffers 4 128k;

        # Max upload body = 60MB (video + image + product photo bisa ~50MB)
        client_max_body_size 60m;

       location / {
           proxy_pass         http://127.0.0.1:8000;
           proxy_http_version 1.1;
           proxy_set_header   Upgrade $http_upgrade;
           proxy_set_header   Connection "upgrade";
           proxy_set_header   Host $host;
           proxy_set_header   X-Real-IP $remote_addr;
           proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header   X-Forwarded-Proto $scheme;

        # Timeout cukup lama untuk upload file besar
        proxy_read_timeout 300s;
        proxy_connect_timeout 60s;
        proxy_send_timeout 300s;

        # Buffer untuk proxy
        proxy_request_buffering on;

       }

}
